version: '3.9'

networks:
  MealMind.Network:
    name: MealMind.Network

services:
  mealmind.postgres:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: MealMind.Postgres
    hostname: MealMind.Postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./.container/postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d MealMind" ]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - MealMind.Network

  mealmind.api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOTNET_VERSION: "10.0"
        BUILD_CONFIGURATION: "Release"
    container_name: MealMind.Api
    depends_on:
      mealmind.postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      postgres__connectionString: "Host=mealmind.postgres;Port=5432;Database=MealMind;Username=postgres;Password="
#      jwt__issuer: "MealMind"
#      jwt__audience: "MealMind"
#      jwt__SecretKey: "YourSuperSecretKeyHere"
#      jwt__expiry: "12:00:00"
    ports:
      - "8080:8080"
    networks:
      - MealMind.Network

  mealmind.ollama:
    image: ollama/ollama:latest
    container_name: MealMind.Ollama
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - MealMind.Network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  postgres:
    driver: local
  ollama_data:
    driver: local